name: ContribuCraft
main: com.com.contribucraft.contribucraft.ContribuCraft
version: 1.0
authors: [JerryWood, TekkitCommando, Phillmac, Jerzean, Lonnie Gibson]
description: A Minecraft plugin for donations and contributions.
website: http://contribucraft.com
api-version: 1.12

commands:
  ping:
    description: Check the ping of the server.
    usage: /ping
    permission: contribucraft.ping
  check:
    description: Check for donations.
    usage: /check
    permission: contribucraft.check
  help:
    description: Show plugin help.
    usage: /help
    permission: contribucraft.help
  apikey:
    description: Set the API key for the plugin.
    usage: /apikey <key>
    permission: contribucraft.apikey
  top:
    description: Show the top contributors.
    usage: /top [page]
    permission: contribucraft.top

permissions:
  contribucraft.ping:
    default: true
    description: Allows players to check the server's ping.
  contribucraft.check:
    default: op
    description: Allows players to check for donations.
  contribucraft.help:
    default: true
    description: Allows players to view the plugin help.
  contribucraft.apikey:
    default: op
    description: Allows players to set the plugin's API key.
  contribucraft.top:
    default: true
    description: Allows players to view the top contributors.
